209 get google sheets data
OpenFn/ConSoSci pull request #210
Opened 2024-04-09 09:57 UTC by hunterachieng

## Summary

Write jobs to allow a user to fetch data from google sheets and then use them to get more form details from Kobo

## Implementation Details

Currently a manual and tedious process is being used to map and write the current google Sheets data. This implementation will focus on writing a job to automatically fetch google sheets data.

## Issues

Fixes #209

### QA Check

**1. Get google sheets data**
>adaptor: googlesheets@2.3.0
```json
{
  "accessToken": "Use 'gcloud auth print-access-token'" 
}

```
Read the following document as a quick start guide to creating your own access token
[Goole OAuth](https://blog.postman.com/how-to-access-google-apis-using-oauth-in-postman/)

2024-04-09 10:14 UTC, mtuchi commented on bns/getKoboData.js
> +    state.sheetsData = filteredSheetsData.map(item => {
Hiya @hunterachieng i think we can improve this logic here 

```
const mapHeaderToValue = (value) => {
  headers.reduce((obj, header) => {
    obj[header] = value[headers.indexOf(header)];
    return obj;
  }, {});
};

state.sheetsData = values
  .filter(
    (item) =>
      item.includes("TRUE") && item.includes("bns_survey", "nrgt_current")
  )
  .map((item) => mapHeaderToValue(item));

```
I am not sure if `mapHeaderToValue()` is the right function name but the idea is to decouple the mapping of key value pair for each column.

2024-04-09 10:18 UTC, mtuchi commented on bns/getKoboData.js
> +        return item;
You don't have to say `return item`. The callback function that `array.filter(cbFn)` takes, should return a true value to keep the element in the resulting array. [See MDN  docs on Array.filter() to learn more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

2024-04-09 10:20 UTC, mtuchi commented on bns/getKoboData.js
>  alterState(state => {
Please use `fn()` instead of ~alterState()~

2024-04-09 11:26 UTC, mtuchi requested changes
@hunterachieng i left some comments for you, also watch on the slack thread on implementation regarding refactoring the nested `each` operations. No action plan yet so don't implement any of the suggestion in that thread unless @aleksa-krolls gives you a go ahead

2024-04-10 07:34 UTC, mtuchi approved these changes
@hunterachieng this looks good

2024-08-22 04:41 UTC, aleksa-krolls approved these changes

2024-08-22 04:42 UTC, merged